name: agora_sdk_engine
description: Agora sdk helper package with caller screen.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  agora_chat_sdk: ^1.0.9
  agora_rtc_engine: ^6.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  fluttertoast: ^8.2.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
